id: e8fd62ac-fa03-44e4-81d6-40c9fb8e4c68
fieldId: a2049e2a-cfcb-475c-9610-14c71b9e385a
description: "Training Module Type, such as video training, interactive/gaming, or coursework"
displayName: "Training Module Type"
values:
  - TRAINING_MODULE: "Training Module"
  - VIDEO_MODULE: "Video Training Module"
  - GAME: "Gamification and Interactive Training Module"
  - ASSESSMENT: "Assessment Training Module"
  - OTHER: "Other"