id: 5ecf4d85-1e8a-465f-b459-40431667a1ce
example: "CompTIA, KnowBe4"
description: "Name of a training module provider such as a credentialing organization, institution, or publisher"
displayName: "Provider"
type: "string"
