id: ea2402b7-62f8-5a3a-9377-889932c11a1b
description: "A copy of files and programs made to facilitate recovery if necessary"
icon: images/classes/auditmation/base/BackupApplication.svg
extends:
  - CryptoDevice
  - Application
properties:
  - backupProfile:
    multi: true
    linkTo: BackupProfile
  - backupJobs:
    multi: true
    linkTo: BackupJob
