id: 4c5ae9a8-5798-59a5-bcc2-3bfe3f922bb0
icon: images/classes/auditmation/base/Database.svg
description: "A Configuration for an Asset"
extends: 
properties:
  - parameters:
    field: parameter
    multi: true
  - assets:
    linkTo: Asset
    multi: true
