id: 9318714f-bb0c-58e1-9f29-349ea9c123db
description: An inventory application
displayName: Inventory Application
extends:
  - Application
properties:
# LInks
  - inventory:
    multi: true
    linkTo: InventoryItem
