id: 8821a472-8ce5-5273-872b-ee7b721eb188
description: "Security Training Campaign"
extends: 
 - Group
icon: images/classes/auditmation/base/Group.svg
properties:
  - trainingCampaigns:
    multi: true
    linkTo: TrainingCampaign
  - phishingCampaigns:
    multi: true
    linkTo: PhishingCampaign