description: "Security Training Campaign"
extends: 
 - Campaign
icon: images/classes/auditmation/base/Campaign.svg
properties:
# Links
  - groups:
    multi: true
    linkTo: TrainingGroup
  - modules:
    multi: true
    linkTo: TrainingModule