id: 238213ab-3123-59d4-8fe7-5ed320a95187
description: "Security Training Campaign"
extends: 
 - Campaign
icon: images/classes/auditmation/base/Campaign.svg
properties:
# Links
  - groups:
    multi: true
    linkTo: TrainingGroup
  - modules:
    multi: true
    linkTo: TrainingModule